#!/bin/sh

echo "$(date -I'seconds') INFO Initial load from Traefik API"
su -s /bin/bash -c "/opt/check/scripts/exec.sh" nobody

cron="${custom_cron:-"*/5 * * * *"}"
echo "${cron} nobody  /opt/check/scripts/exec.sh" >> /etc/crontabs/root 

echo "$(date -I'seconds') INFO Initial load from Traefik API DONE"

exec "$@"
